### ISSUE TITLE
octant start failed: 	prowjobs.prow.k8s.io: crd conversion failed: cannot convert int64 to float64

### ISSUE THREAD

**Issue by rootsongjc** [vmware/octant#169]
## Environment

MacOS Mojave version 10.14.6

**Kubernetes Verion**

- Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
- Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

## Error messages

```
2019-08-15T11:02:27.652+0800	INFO	module/manager.go:75	registering action	{"component": "module-manager", "actionPath": "deployment/configuration", "module-name": "overview"}
2019-08-15T11:02:27.654+0800	INFO	api/content.go:52	Registering routes for overview
2019-08-15T11:02:27.654+0800	INFO	api/content.go:52	Registering routes for cluster-overview
2019-08-15T11:02:27.655+0800	INFO	api/content.go:52	Registering routes for configuration
2019-08-15T11:02:27.655+0800	INFO	dash/dash.go:335	Dashboard is available at http://127.0.0.1:63417

2019-08-15T11:02:29.054+0800	ERROR	navigation/navigation.go:125	prowjobs.prow.k8s.io: crd conversion failed: cannot convert int64 to float64
github.com/vmware/octant/pkg/navigation.CustomResourceDefinitions
	/go/src/github.com/vmware/octant/pkg/navigation/navigation.go:125
github.com/vmware/octant/pkg/navigation.CRDEntries
	/go/src/github.com/vmware/octant/pkg/navigation/navigation.go:74
github.com/vmware/octant/internal/octant.(*NavigationFactory).genNode
	/go/src/github.com/vmware/octant/internal/octant/factory.go:115
github.com/vmware/octant/internal/octant.(*NavigationFactory).Generate.func1
	/go/src/github.com/vmware/octant/internal/octant/factory.go:83
github.com/vmware/octant/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1
	/go/src/github.com/vmware/octant/vendor/golang.org/x/sync/errgroup/errgroup.go:57
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1e16d53]

goroutine 234 [running]:
github.com/vmware/octant/pkg/navigation.CRDEntries.func1(0x3, 0x2, 0xc00119c000)
	/go/src/github.com/vmware/octant/pkg/navigation/navigation.go:80 +0x33
sort.insertionSort_func(0xc000455d38, 0xc000350980, 0x0, 0x7)
	/usr/local/go/src/sort/zfuncversion.go:12 +0xb1
sort.quickSort_func(0xc000455d38, 0xc000350980, 0x0, 0x7, 0x6)
	/usr/local/go/src/sort/zfuncversion.go:158 +0x1f3
sort.Slice(0x211d400, 0xc000350940, 0xc000455d38)
	/usr/local/go/src/sort/slice.go:21 +0x129
github.com/vmware/octant/pkg/navigation.CRDEntries(0x29b8620, 0xc000292240, 0xc00114e3f0, 0x2a, 0x0, 0x0, 0x29cd260, 0xc0011d6480, 0x0, 0x0, ...)
	/go/src/github.com/vmware/octant/pkg/navigation/navigation.go:79 +0x124
github.com/vmware/octant/internal/octant.(*NavigationFactory).genNode(0xc001343800, 0x29b8620, 0xc000292240, 0x23d9308, 0x10, 0x27d7158, 0xc0012513a0, 0xc001150960, 0x23d5f9c)
	/go/src/github.com/vmware/octant/internal/octant/factory.go:115 +0x269
github.com/vmware/octant/internal/octant.(*NavigationFactory).Generate.func1(0xc000000008, 0x27da070)
	/go/src/github.com/vmware/octant/internal/octant/factory.go:83 +0xeb
github.com/vmware/octant/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc001150a80, 0xc001345ec0)
	/go/src/github.com/vmware/octant/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x57
created by github.com/vmware/octant/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/go/src/github.com/vmware/octant/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```

**Comment by bryanl** [comment]
Hello, this was fixed in #145 and will be a part of our 0.6 release.
